# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
 - git config --global core.autocrlf true

# scripts that run after cloning repository
install:
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

# scripts to run before build
before_build:
 - set PATH=%USERPROFILE%\.dnx\bin;%PATH%
# - ps: $version = (Get-Content ./src/project.json | ConvertFrom-Json).version + "+{build}"
# - ps: Update-AppveyorBuild -Version $version
#- ps: dnvm install 1.0.0-beta7
 - ps: dnvm upgrade
#- ps: dnvm update-self
#- ps: dnvm list
#- ps: dnvm use 1.0.0-beta7
#- ps: npm cache clean
 - ps: npm install -g gulp bower
 - ps: dnu restore

# to run your custom scripts instead of automatic MSBuild
build_script:
 - ps: dnu build ./src
 - ps: dnu publish ./src --configuration Release -o AppOutput --no-source --runtime "active"

# to run your custom scripts instead of automatic tests
test_script:
 - ps: dnx -p .\test test

artifacts:
 - path: /AppOutput
   name: AppOutput

deploy:
 - provider: Environment
   name: Demo
   website_name: aspnet5rc3
#   on:
#    appveyor_repo_tag: true       # deploy on tag push only
#   branch: master                # release from master branch only    

after_deploy:
# - ps: Disable-AzureDataCollection
 - ps: Select-AzureSubscription -Current -SubscriptionName "Visual Studio Premium with MSDN"
 - ps: Restart-AzureWebsite -Name "aspnet5rc3"

notifications:
 - provider: Slack
   incoming_webhook: https://hooks.slack.com/services/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
   channel: general
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true
