# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
 - git config --global core.autocrlf true

# scripts that run after cloning repository
install:
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

# scripts to run before build
before_build:
 - set PATH=%USERPROFILE%\.dnx\bin;%PATH%
#- ps: dnvm install 1.0.0-beta7
 - ps: dnvm upgrade
#- ps: dnvm update-self
#- ps: dnvm list
#- ps: dnvm use 1.0.0-beta7
#- ps: npm cache clean
 - ps: npm install -g gulp bower
 - ps: dnu restore

# to run your custom scripts instead of automatic MSBuild
build_script:
 - ps: dnu build ./src
 - ps: dnu publish ./src --configuration Release -o AppOutput --no-source --runtime "active"

# to run your custom scripts instead of automatic tests
test_script:
 - ps: dnx -p .\test test

artifacts:
 - path: /AppOutput
   name: AppOutput

deploy:
 - provider: Environment
   name: Demo
   on:
	branch: master                # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only   

# Web Deploy deployment provider settings
# - provider: WebDeploy
#   server: https://aspnet5rc2.scm.azurewebsites.net:443/msdeploy.axd?site=aspnet5rc2
#   website: aspnet5rc2
#   username: $aspnet5rc2
#   password:
#    secure: SULiqIVeN1vB8S2A786UGTz4ehYV5TVQUmiPcEDWYvQgPM6tZqafK1gFZpkG9/xCF7rnF5SFj3zaSKy/RYh/HQ==
#   app_offline: true
#   aspnet5: true

# on:
# branch: master

notifications:
 - provider: Slack
   incoming_webhook: https://hooks.slack.com/services/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
   channel: general
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true
