# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
 - git config --global core.autocrlf true

# scripts that run after cloning repository
install:
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

# scripts to run before build
before_build:
 - set PATH=%USERPROFILE%\.dnx\bin;%PATH%
#- ps: dnvm install 1.0.0-beta7
 - ps: dnvm upgrade
#- ps: dnvm update-self
#- ps: dnvm list
#- ps: dnvm use 1.0.0-beta7
#- ps: npm cache clean
 - ps: npm install -g gulp bower
 - ps: dnu restore

# to run your custom scripts instead of automatic MSBuild
build_script:
 - ps: dnu build ./src
 - ps: dnu publish ./src --configuration Release -o AppOutput --no-source --runtime "active"
 
# to run your custom scripts instead of automatic tests
test_script: 
 - ps: dnx -p .\test test
 
artifacts:
 - path: /AppOutput
   name: AppOutput
   
deploy:

 # Web Deploy deployment provider settings
 - provider: WebDeploy
   server: https://aspnet5mvc6.scm.azurewebsites.net:443/msdeploy.axd?site=aspnet5mvc6
   website: aspnet5mvc6
   username: $aspnet5mvc6
   password: AFHm8kLLRms6nfoK5XLbMg42b74rAdets5sgzRgJkEMgaBltpivJXehagben
   ntlm: false
   remove_files: true
   app_offline: false
   artifact: AppOutput
   
#on:
#branch: master
