# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
 - git config --global core.autocrlf true

# scripts that run after cloning repository
install:
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 - ps: $env:DNX_BUILD_VERSION = $env:APPVEYOR_BUILD_NUMBER
 - ps: $sha = "$env:APPVEYOR_REPO_COMMIT".substring(0,7)
 - ps: $env:MY_BUILD_TAG = "$env:APPVEYOR_BUILD_NUMBER.$env:APPVEYOR_REPO_BRANCH.$sha"
 - ps: $json = Get-Content .\src\project.json -Raw | ConvertFrom-Json
 - ps: $version = $json.version -replace "\*", $env:MY_BUILD_TAG
 - ps: Update-AppveyorBuild -Version $version
# - ps: Update-AppveyorBuild -Version "$version+$env:MY_BUILD_TAG"

# scripts to run before build
before_build:
 - set PATH=%USERPROFILE%\.dnx\bin;%PATH%
#- ps: dnvm install 1.0.0-beta7
 - dnvm upgrade
#- ps: dnvm update-self
#- ps: dnvm list
#- ps: dnvm use 1.0.0-beta7
 - npm cache clean
# - ps: npm install gulp bower
 - npm install -g gulp bower
 - dnu restore

# to run your custom scripts instead of automatic MSBuild
build_script:
 - dnu build ./src
 - dnu publish ./src --configuration Release -o AppOutput --runtime "active" --wwwroot "wwwroot" --wwwroot-out "wwwroot" --iis-command "web" --quiet

# to run your custom scripts instead of automatic tests
#test_script:
# - ps: dnx -p .\test test

artifacts:
 - path: /AppOutput
   name: AppOutput

deploy:
 - provider: Environment
   name: Demo
   website_name: aspnet5rc3
   on:
    appveyor_repo_tag: true

 - provider: Environment
   name: Test
   website_name: aspnet5rc2
   remove_files: true
#    on:
#     APPVEYOR_PULL_REQUEST_NUMBER: /\d+/
#   on:
#    branch: master

notifications:
 - provider: Slack
   incoming_webhook: https://hooks.slack.com/services/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
   channel: general
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true
 - provider: GitHubPullRequest
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true
