# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
 - git config --global core.autocrlf true

# scripts that run after cloning repository
install:
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

# scripts to run before build
before_build:
 - set PATH=%USERPROFILE%\.dnx\bin;%PATH%
#- ps: dnvm install 1.0.0-beta7
 - ps: dnvm upgrade
#- ps: dnvm update-self
#- ps: dnvm list
#- ps: dnvm use 1.0.0-beta7
#- ps: npm cache clean
#- ps: npm install -g gulp bower
 - ps: dnu restore

# to run your custom scripts instead of automatic MSBuild
build_script:
 - ps: cd .\src;dnu build
 - ps: cd .\test;dnx test
