init:
  - git config --global core.autocrlf true
  
before_build:
 - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 #- ps: dnvm install 1.0.0-beta6
 - cmd: dnvm upgrade
 #- ps: dnvm use 1.0.0-beta6
 #- ps: dnvm list
 #- ps: npm cache clean
 #- ps: npm install -g gulp bower
 - cmd: dnu restore
 
build_script:
  - cmd: cd src/ && dnu build
  
clone_depth: 1

test: off

deploy: off

#notifications:
#  - provider: Slack
#    incoming_webhook: https://hooks.slack.com/services/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 
