init:
  - git config --global core.autocrlf true
install:
  - cmd: @powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  - cmd: dnvm upgrade
  - cmd: dnu restore
build_script:
  - cd src/ && dnu build
clone_depth: 1
test: off
deploy: off
notifications:
# Slack
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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 
