init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd --quiet --parallel verify
clone_depth: 1
test: off
deploy: off
artifacts:
  - path: artifacts/build/Xunit.KRunner.AppVeyor.*.nupkg
notifications:
# Slack
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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 
